//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capstone6NonIdentity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        public Nullable<int> UserID { get; set; }
        public int TaskID { get; set; }
        public string Description { get; set; }
        public string DueDate { get; set; }
        public bool Complete { get; set; }
    }
}
